//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuditEventSeverity-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuditEventSeverity-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="emergency"/>
 *     &lt;enumeration value="alert"/>
 *     &lt;enumeration value="critical"/>
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="warning"/>
 *     &lt;enumeration value="notice"/>
 *     &lt;enumeration value="informational"/>
 *     &lt;enumeration value="debug"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuditEventSeverity-list")
@XmlEnum
public enum AuditEventSeverityList {


    /**
     * Emergency
     * 
     */
    @XmlEnumValue("emergency")
    EMERGENCY("emergency"),

    /**
     * Alert
     * 
     */
    @XmlEnumValue("alert")
    ALERT("alert"),

    /**
     * Critical
     * 
     */
    @XmlEnumValue("critical")
    CRITICAL("critical"),

    /**
     * Error
     * 
     */
    @XmlEnumValue("error")
    ERROR("error"),

    /**
     * Warning
     * 
     */
    @XmlEnumValue("warning")
    WARNING("warning"),

    /**
     * Notice
     * 
     */
    @XmlEnumValue("notice")
    NOTICE("notice"),

    /**
     * Informational
     * 
     */
    @XmlEnumValue("informational")
    INFORMATIONAL("informational"),

    /**
     * Debug
     * 
     */
    @XmlEnumValue("debug")
    DEBUG("debug");
    private final java.lang.String value;

    AuditEventSeverityList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static AuditEventSeverityList fromValue(java.lang.String v) {
        for (AuditEventSeverityList c: AuditEventSeverityList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
