//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an @id referenced from the Narrative, or extensions
 * 
 * <p>Java class for BackboneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackboneType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DataType">
 *       &lt;sequence>
 *         &lt;element name="modifierExtension" type="{http://hl7.org/fhir}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackboneType", propOrder = {
    "modifierExtension"
})
@XmlSeeAlso({
    ElementDefinitionSlicing.class,
    ProductShelfLife.class,
    Dosage.class,
    StatisticVariable.class,
    Timing.class,
    MarketingStatus.class,
    Population.class,
    StatisticAttributeEstimate.class,
    StatisticModelCharacteristic.class,
    TimingRepeat.class,
    Statistic.class,
    ElementDefinitionDiscriminator.class,
    ElementDefinitionMapping.class,
    ElementDefinitionBase.class,
    ElementDefinitionConstraint.class,
    ProdCharacteristic.class,
    StatisticSampleSize.class,
    ElementDefinitionType.class,
    DosageDoseAndRate.class,
    ElementDefinitionExample.class,
    ElementDefinition.class,
    StatisticAttributeEstimate1 .class,
    OrderedDistribution.class,
    ElementDefinitionBinding.class,
    OrderedDistributionInterval.class
})
public class BackboneType
    extends DataType
{

    protected List<Extension> modifierExtension;

    /**
     * Gets the value of the modifierExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifierExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifierExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getModifierExtension() {
        if (modifierExtension == null) {
            modifierExtension = new ArrayList<Extension>();
        }
        return this.modifierExtension;
    }

}
