//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A definition of a condition and information relevant to managing it.
 * 
 * <p>Java class for ConditionDefinition.Questionnaire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionDefinition.Questionnaire">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="purpose" type="{http://hl7.org/fhir}ConditionQuestionnairePurpose"/>
 *         &lt;element name="reference" type="{http://hl7.org/fhir}Reference"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionDefinition.Questionnaire", propOrder = {
    "purpose",
    "reference"
})
public class ConditionDefinitionQuestionnaire
    extends BackboneElement
{

    @XmlElement(required = true)
    protected ConditionQuestionnairePurpose purpose;
    @XmlElement(required = true)
    protected Reference reference;

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionQuestionnairePurpose }
     *     
     */
    public ConditionQuestionnairePurpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionQuestionnairePurpose }
     *     
     */
    public void setPurpose(ConditionQuestionnairePurpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

}
