//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for Event Or Request Resource Types complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event Or Request Resource Types">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}Element">
 *       &lt;attribute name="value" type="{http://hl7.org/fhir}Event Or Request Resource Types-list" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event Or Request Resource Types")
public class Event_0020Or_0020Request_0020Resource_0020Types
    extends Element
{

    @XmlAttribute(name = "value")
    protected Event_0020Or_0020Request_0020Resource_0020TypesList value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Event_0020Or_0020Request_0020Resource_0020TypesList }
     *     
     */
    public Event_0020Or_0020Request_0020Resource_0020TypesList getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event_0020Or_0020Request_0020Resource_0020TypesList }
     *     
     */
    public void setValue(Event_0020Or_0020Request_0020Resource_0020TypesList value) {
        this.value = value;
    }

}
