//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for MedicationKnowledge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicationKnowledge">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="code" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="status" type="{http://hl7.org/fhir}code" minOccurs="0"/>
 *         &lt;element name="author" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="doseForm" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="amount" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="synonym" type="{http://hl7.org/fhir}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relatedMedicationKnowledge" type="{http://hl7.org/fhir}MedicationKnowledge.RelatedMedicationKnowledge" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="associatedMedication" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="associatedDefinition" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="productType" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="monograph" type="{http://hl7.org/fhir}MedicationKnowledge.Monograph" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ingredient" type="{http://hl7.org/fhir}MedicationKnowledge.Ingredient" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="device" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="preparationInstruction" type="{http://hl7.org/fhir}markdown" minOccurs="0"/>
 *         &lt;element name="intendedRoute" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cost" type="{http://hl7.org/fhir}MedicationKnowledge.Cost" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="monitoringProgram" type="{http://hl7.org/fhir}MedicationKnowledge.MonitoringProgram" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="administrationGuideline" type="{http://hl7.org/fhir}MedicationKnowledge.AdministrationGuideline" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="medicineClassification" type="{http://hl7.org/fhir}MedicationKnowledge.MedicineClassification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="packaging" type="{http://hl7.org/fhir}MedicationKnowledge.Packaging" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="drugCharacteristic" type="{http://hl7.org/fhir}MedicationKnowledge.DrugCharacteristic" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clinicalUseIssue" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regulatory" type="{http://hl7.org/fhir}MedicationKnowledge.Regulatory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kineticCharacteristic" type="{http://hl7.org/fhir}MedicationKnowledge.KineticCharacteristic" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicationKnowledge", propOrder = {
    "identifier",
    "code",
    "status",
    "author",
    "manufacturer",
    "doseForm",
    "amount",
    "synonym",
    "relatedMedicationKnowledge",
    "associatedMedication",
    "associatedDefinition",
    "productType",
    "monograph",
    "ingredient",
    "device",
    "preparationInstruction",
    "intendedRoute",
    "cost",
    "monitoringProgram",
    "administrationGuideline",
    "medicineClassification",
    "packaging",
    "drugCharacteristic",
    "clinicalUseIssue",
    "regulatory",
    "kineticCharacteristic"
})
public class MedicationKnowledge
    extends DomainResource
{

    protected List<Identifier> identifier;
    protected CodeableConcept code;
    protected Code status;
    protected Reference author;
    protected Reference manufacturer;
    protected CodeableConcept doseForm;
    protected Quantity amount;
    protected List<String> synonym;
    protected List<MedicationKnowledgeRelatedMedicationKnowledge> relatedMedicationKnowledge;
    protected List<Reference> associatedMedication;
    protected Reference associatedDefinition;
    protected List<CodeableConcept> productType;
    protected List<MedicationKnowledgeMonograph> monograph;
    protected List<MedicationKnowledgeIngredient> ingredient;
    protected List<Reference> device;
    protected Markdown preparationInstruction;
    protected List<CodeableConcept> intendedRoute;
    protected List<MedicationKnowledgeCost> cost;
    protected List<MedicationKnowledgeMonitoringProgram> monitoringProgram;
    protected List<MedicationKnowledgeAdministrationGuideline> administrationGuideline;
    protected List<MedicationKnowledgeMedicineClassification> medicineClassification;
    protected List<MedicationKnowledgePackaging> packaging;
    protected List<MedicationKnowledgeDrugCharacteristic> drugCharacteristic;
    protected List<Reference> clinicalUseIssue;
    protected List<MedicationKnowledgeRegulatory> regulatory;
    protected List<MedicationKnowledgeKineticCharacteristic> kineticCharacteristic;

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setCode(CodeableConcept value) {
        this.code = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setStatus(Code value) {
        this.status = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAuthor(Reference value) {
        this.author = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setManufacturer(Reference value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the doseForm property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getDoseForm() {
        return doseForm;
    }

    /**
     * Sets the value of the doseForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setDoseForm(CodeableConcept value) {
        this.doseForm = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setAmount(Quantity value) {
        this.amount = value;
    }

    /**
     * Gets the value of the synonym property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synonym property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynonym().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSynonym() {
        if (synonym == null) {
            synonym = new ArrayList<String>();
        }
        return this.synonym;
    }

    /**
     * Gets the value of the relatedMedicationKnowledge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedMedicationKnowledge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedMedicationKnowledge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeRelatedMedicationKnowledge }
     * 
     * 
     */
    public List<MedicationKnowledgeRelatedMedicationKnowledge> getRelatedMedicationKnowledge() {
        if (relatedMedicationKnowledge == null) {
            relatedMedicationKnowledge = new ArrayList<MedicationKnowledgeRelatedMedicationKnowledge>();
        }
        return this.relatedMedicationKnowledge;
    }

    /**
     * Gets the value of the associatedMedication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedMedication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedMedication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getAssociatedMedication() {
        if (associatedMedication == null) {
            associatedMedication = new ArrayList<Reference>();
        }
        return this.associatedMedication;
    }

    /**
     * Gets the value of the associatedDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAssociatedDefinition() {
        return associatedDefinition;
    }

    /**
     * Sets the value of the associatedDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAssociatedDefinition(Reference value) {
        this.associatedDefinition = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getProductType() {
        if (productType == null) {
            productType = new ArrayList<CodeableConcept>();
        }
        return this.productType;
    }

    /**
     * Gets the value of the monograph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monograph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonograph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeMonograph }
     * 
     * 
     */
    public List<MedicationKnowledgeMonograph> getMonograph() {
        if (monograph == null) {
            monograph = new ArrayList<MedicationKnowledgeMonograph>();
        }
        return this.monograph;
    }

    /**
     * Gets the value of the ingredient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeIngredient }
     * 
     * 
     */
    public List<MedicationKnowledgeIngredient> getIngredient() {
        if (ingredient == null) {
            ingredient = new ArrayList<MedicationKnowledgeIngredient>();
        }
        return this.ingredient;
    }

    /**
     * Gets the value of the device property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the device property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDevice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getDevice() {
        if (device == null) {
            device = new ArrayList<Reference>();
        }
        return this.device;
    }

    /**
     * Gets the value of the preparationInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link Markdown }
     *     
     */
    public Markdown getPreparationInstruction() {
        return preparationInstruction;
    }

    /**
     * Sets the value of the preparationInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markdown }
     *     
     */
    public void setPreparationInstruction(Markdown value) {
        this.preparationInstruction = value;
    }

    /**
     * Gets the value of the intendedRoute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intendedRoute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntendedRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getIntendedRoute() {
        if (intendedRoute == null) {
            intendedRoute = new ArrayList<CodeableConcept>();
        }
        return this.intendedRoute;
    }

    /**
     * Gets the value of the cost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeCost }
     * 
     * 
     */
    public List<MedicationKnowledgeCost> getCost() {
        if (cost == null) {
            cost = new ArrayList<MedicationKnowledgeCost>();
        }
        return this.cost;
    }

    /**
     * Gets the value of the monitoringProgram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monitoringProgram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonitoringProgram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeMonitoringProgram }
     * 
     * 
     */
    public List<MedicationKnowledgeMonitoringProgram> getMonitoringProgram() {
        if (monitoringProgram == null) {
            monitoringProgram = new ArrayList<MedicationKnowledgeMonitoringProgram>();
        }
        return this.monitoringProgram;
    }

    /**
     * Gets the value of the administrationGuideline property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the administrationGuideline property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdministrationGuideline().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeAdministrationGuideline }
     * 
     * 
     */
    public List<MedicationKnowledgeAdministrationGuideline> getAdministrationGuideline() {
        if (administrationGuideline == null) {
            administrationGuideline = new ArrayList<MedicationKnowledgeAdministrationGuideline>();
        }
        return this.administrationGuideline;
    }

    /**
     * Gets the value of the medicineClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicineClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicineClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeMedicineClassification }
     * 
     * 
     */
    public List<MedicationKnowledgeMedicineClassification> getMedicineClassification() {
        if (medicineClassification == null) {
            medicineClassification = new ArrayList<MedicationKnowledgeMedicineClassification>();
        }
        return this.medicineClassification;
    }

    /**
     * Gets the value of the packaging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packaging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackaging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgePackaging }
     * 
     * 
     */
    public List<MedicationKnowledgePackaging> getPackaging() {
        if (packaging == null) {
            packaging = new ArrayList<MedicationKnowledgePackaging>();
        }
        return this.packaging;
    }

    /**
     * Gets the value of the drugCharacteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugCharacteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeDrugCharacteristic }
     * 
     * 
     */
    public List<MedicationKnowledgeDrugCharacteristic> getDrugCharacteristic() {
        if (drugCharacteristic == null) {
            drugCharacteristic = new ArrayList<MedicationKnowledgeDrugCharacteristic>();
        }
        return this.drugCharacteristic;
    }

    /**
     * Gets the value of the clinicalUseIssue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinicalUseIssue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClinicalUseIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getClinicalUseIssue() {
        if (clinicalUseIssue == null) {
            clinicalUseIssue = new ArrayList<Reference>();
        }
        return this.clinicalUseIssue;
    }

    /**
     * Gets the value of the regulatory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regulatory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegulatory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeRegulatory }
     * 
     * 
     */
    public List<MedicationKnowledgeRegulatory> getRegulatory() {
        if (regulatory == null) {
            regulatory = new ArrayList<MedicationKnowledgeRegulatory>();
        }
        return this.regulatory;
    }

    /**
     * Gets the value of the kineticCharacteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kineticCharacteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKineticCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationKnowledgeKineticCharacteristic }
     * 
     * 
     */
    public List<MedicationKnowledgeKineticCharacteristic> getKineticCharacteristic() {
        if (kineticCharacteristic == null) {
            kineticCharacteristic = new ArrayList<MedicationKnowledgeKineticCharacteristic>();
        }
        return this.kineticCharacteristic;
    }

}
