//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedlineCitationOwner-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MedlineCitationOwner-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="NLM"/>
 *     &lt;enumeration value="NASA"/>
 *     &lt;enumeration value="PIP"/>
 *     &lt;enumeration value="KIE"/>
 *     &lt;enumeration value="HSR"/>
 *     &lt;enumeration value="HMD"/>
 *     &lt;enumeration value="SIS"/>
 *     &lt;enumeration value="NOTNLM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MedlineCitationOwner-list")
@XmlEnum
public enum MedlineCitationOwnerList {


    /**
     * NLM
     * 
     */
    NLM,

    /**
     * NASA
     * 
     */
    NASA,

    /**
     * PIP
     * 
     */
    PIP,

    /**
     * KIE
     * 
     */
    KIE,

    /**
     * HSR
     * 
     */
    HSR,

    /**
     * HMD
     * 
     */
    HMD,

    /**
     * SIS
     * 
     */
    SIS,

    /**
     * NOTNLM
     * 
     */
    NOTNLM;

    public java.lang.String value() {
        return name();
    }

    public static MedlineCitationOwnerList fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
