//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportRelationshipType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReportRelationshipType-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="replaces"/>
 *     &lt;enumeration value="amends"/>
 *     &lt;enumeration value="appends"/>
 *     &lt;enumeration value="transforms"/>
 *     &lt;enumeration value="replacedWith"/>
 *     &lt;enumeration value="amendedWith"/>
 *     &lt;enumeration value="appendedWith"/>
 *     &lt;enumeration value="transformedWith"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReportRelationshipType-list")
@XmlEnum
public enum ReportRelationshipTypeList {


    /**
     * Replaces
     * 
     */
    @XmlEnumValue("replaces")
    REPLACES("replaces"),

    /**
     * Amends
     * 
     */
    @XmlEnumValue("amends")
    AMENDS("amends"),

    /**
     * Appends
     * 
     */
    @XmlEnumValue("appends")
    APPENDS("appends"),

    /**
     * Transforms
     * 
     */
    @XmlEnumValue("transforms")
    TRANSFORMS("transforms"),

    /**
     * Replaced With
     * 
     */
    @XmlEnumValue("replacedWith")
    REPLACED_WITH("replacedWith"),

    /**
     * Amended With
     * 
     */
    @XmlEnumValue("amendedWith")
    AMENDED_WITH("amendedWith"),

    /**
     * Appended With
     * 
     */
    @XmlEnumValue("appendedWith")
    APPENDED_WITH("appendedWith"),

    /**
     * Transformed With
     * 
     */
    @XmlEnumValue("transformedWith")
    TRANSFORMED_WITH("transformedWith");
    private final java.lang.String value;

    ReportRelationshipTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ReportRelationshipTypeList fromValue(java.lang.String v) {
        for (ReportRelationshipTypeList c: ReportRelationshipTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
