//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionPayloadContent-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubscriptionPayloadContent-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="empty"/>
 *     &lt;enumeration value="id-only"/>
 *     &lt;enumeration value="full-resource"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SubscriptionPayloadContent-list")
@XmlEnum
public enum SubscriptionPayloadContentList {


    /**
     * empty
     * 
     */
    @XmlEnumValue("empty")
    EMPTY("empty"),

    /**
     * id-only
     * 
     */
    @XmlEnumValue("id-only")
    ID_ONLY("id-only"),

    /**
     * full-resource
     * 
     */
    @XmlEnumValue("full-resource")
    FULL_RESOURCE("full-resource");
    private final java.lang.String value;

    SubscriptionPayloadContentList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SubscriptionPayloadContentList fromValue(java.lang.String v) {
        for (SubscriptionPayloadContentList c: SubscriptionPayloadContentList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
