//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionNotificationType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubscriptionNotificationType-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="handshake"/>
 *     &lt;enumeration value="heartbeat"/>
 *     &lt;enumeration value="event-notification"/>
 *     &lt;enumeration value="query-status"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SubscriptionNotificationType-list")
@XmlEnum
public enum SubscriptionNotificationTypeList {


    /**
     * Handshake
     * 
     */
    @XmlEnumValue("handshake")
    HANDSHAKE("handshake"),

    /**
     * Heartbeat
     * 
     */
    @XmlEnumValue("heartbeat")
    HEARTBEAT("heartbeat"),

    /**
     * Event Notification
     * 
     */
    @XmlEnumValue("event-notification")
    EVENT_NOTIFICATION("event-notification"),

    /**
     * Query Status
     * 
     */
    @XmlEnumValue("query-status")
    QUERY_STATUS("query-status");
    private final java.lang.String value;

    SubscriptionNotificationTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SubscriptionNotificationTypeList fromValue(java.lang.String v) {
        for (SubscriptionNotificationTypeList c: SubscriptionNotificationTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
