//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A medicinal product in the final form which is suitable for administering to a patient (after any mixing of multiple components, dissolution etc. has been performed).
 * 
 * <p>Java class for AdministrableProductDefinition.RouteOfAdministration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdministrableProductDefinition.RouteOfAdministration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://hl7.org/fhir}CodeableConcept"/>
 *         &lt;element name="firstDose" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="maxSingleDose" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="maxDosePerDay" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="maxDosePerTreatmentPeriod" type="{http://hl7.org/fhir}Ratio" minOccurs="0"/>
 *         &lt;element name="maxTreatmentPeriod" type="{http://hl7.org/fhir}Duration" minOccurs="0"/>
 *         &lt;element name="targetSpecies" type="{http://hl7.org/fhir}AdministrableProductDefinition.TargetSpecies" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdministrableProductDefinition.RouteOfAdministration", propOrder = {
    "code",
    "firstDose",
    "maxSingleDose",
    "maxDosePerDay",
    "maxDosePerTreatmentPeriod",
    "maxTreatmentPeriod",
    "targetSpecies"
})
public class AdministrableProductDefinitionRouteOfAdministration
    extends BackboneElement
{

    @XmlElement(required = true)
    protected CodeableConcept code;
    protected Quantity firstDose;
    protected Quantity maxSingleDose;
    protected Quantity maxDosePerDay;
    protected Ratio maxDosePerTreatmentPeriod;
    protected Duration maxTreatmentPeriod;
    protected List<AdministrableProductDefinitionTargetSpecies> targetSpecies;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setCode(CodeableConcept value) {
        this.code = value;
    }

    /**
     * Gets the value of the firstDose property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getFirstDose() {
        return firstDose;
    }

    /**
     * Sets the value of the firstDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setFirstDose(Quantity value) {
        this.firstDose = value;
    }

    /**
     * Gets the value of the maxSingleDose property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getMaxSingleDose() {
        return maxSingleDose;
    }

    /**
     * Sets the value of the maxSingleDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setMaxSingleDose(Quantity value) {
        this.maxSingleDose = value;
    }

    /**
     * Gets the value of the maxDosePerDay property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getMaxDosePerDay() {
        return maxDosePerDay;
    }

    /**
     * Sets the value of the maxDosePerDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setMaxDosePerDay(Quantity value) {
        this.maxDosePerDay = value;
    }

    /**
     * Gets the value of the maxDosePerTreatmentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Ratio }
     *     
     */
    public Ratio getMaxDosePerTreatmentPeriod() {
        return maxDosePerTreatmentPeriod;
    }

    /**
     * Sets the value of the maxDosePerTreatmentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ratio }
     *     
     */
    public void setMaxDosePerTreatmentPeriod(Ratio value) {
        this.maxDosePerTreatmentPeriod = value;
    }

    /**
     * Gets the value of the maxTreatmentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaxTreatmentPeriod() {
        return maxTreatmentPeriod;
    }

    /**
     * Sets the value of the maxTreatmentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxTreatmentPeriod(Duration value) {
        this.maxTreatmentPeriod = value;
    }

    /**
     * Gets the value of the targetSpecies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetSpecies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetSpecies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdministrableProductDefinitionTargetSpecies }
     * 
     * 
     */
    public List<AdministrableProductDefinitionTargetSpecies> getTargetSpecies() {
        if (targetSpecies == null) {
            targetSpecies = new ArrayList<AdministrableProductDefinitionTargetSpecies>();
        }
        return this.targetSpecies;
    }

}
