//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The Citation Resource enables reference to any knowledge artifact for purposes of identification and attribution. The Citation Resource supports existing reference structures and developing publication practices such as versioning, expressing complex contributorship roles, and referencing computable resources.
 * 
 * <p>Java class for Citation.PublicationForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Citation.PublicationForm">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="publishingModel" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="publishedIn" type="{http://hl7.org/fhir}Citation.PublishedIn" minOccurs="0"/>
 *         &lt;element name="periodicRelease" type="{http://hl7.org/fhir}Citation.PeriodicRelease" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="articleDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="revisionDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="language" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pageString" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="firstPage" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="lastPage" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="pageCount" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Citation.PublicationForm", propOrder = {
    "publishingModel",
    "publishedIn",
    "periodicRelease",
    "articleDate",
    "revisionDate",
    "language",
    "pageString",
    "firstPage",
    "lastPage",
    "pageCount"
})
public class CitationPublicationForm
    extends BackboneElement
{

    protected CodeableConcept publishingModel;
    protected CitationPublishedIn publishedIn;
    protected List<CitationPeriodicRelease> periodicRelease;
    protected DateTime articleDate;
    protected DateTime revisionDate;
    protected List<CodeableConcept> language;
    protected String pageString;
    protected String firstPage;
    protected String lastPage;
    protected String pageCount;

    /**
     * Gets the value of the publishingModel property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getPublishingModel() {
        return publishingModel;
    }

    /**
     * Sets the value of the publishingModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setPublishingModel(CodeableConcept value) {
        this.publishingModel = value;
    }

    /**
     * Gets the value of the publishedIn property.
     * 
     * @return
     *     possible object is
     *     {@link CitationPublishedIn }
     *     
     */
    public CitationPublishedIn getPublishedIn() {
        return publishedIn;
    }

    /**
     * Sets the value of the publishedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationPublishedIn }
     *     
     */
    public void setPublishedIn(CitationPublishedIn value) {
        this.publishedIn = value;
    }

    /**
     * Gets the value of the periodicRelease property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodicRelease property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodicRelease().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationPeriodicRelease }
     * 
     * 
     */
    public List<CitationPeriodicRelease> getPeriodicRelease() {
        if (periodicRelease == null) {
            periodicRelease = new ArrayList<CitationPeriodicRelease>();
        }
        return this.periodicRelease;
    }

    /**
     * Gets the value of the articleDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getArticleDate() {
        return articleDate;
    }

    /**
     * Sets the value of the articleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setArticleDate(DateTime value) {
        this.articleDate = value;
    }

    /**
     * Gets the value of the revisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getRevisionDate() {
        return revisionDate;
    }

    /**
     * Sets the value of the revisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setRevisionDate(DateTime value) {
        this.revisionDate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getLanguage() {
        if (language == null) {
            language = new ArrayList<CodeableConcept>();
        }
        return this.language;
    }

    /**
     * Gets the value of the pageString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageString() {
        return pageString;
    }

    /**
     * Sets the value of the pageString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageString(String value) {
        this.pageString = value;
    }

    /**
     * Gets the value of the firstPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPage() {
        return firstPage;
    }

    /**
     * Sets the value of the firstPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPage(String value) {
        this.firstPage = value;
    }

    /**
     * Gets the value of the lastPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPage() {
        return lastPage;
    }

    /**
     * Sets the value of the lastPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPage(String value) {
        this.lastPage = value;
    }

    /**
     * Gets the value of the pageCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageCount(String value) {
        this.pageCount = value;
    }

}
