//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefinitionResourceType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DefinitionResourceType-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="ActivityDefinition"/>
 *     &lt;enumeration value="EventDefinition"/>
 *     &lt;enumeration value="Measure"/>
 *     &lt;enumeration value="OperationDefinition"/>
 *     &lt;enumeration value="PlanDefinition"/>
 *     &lt;enumeration value="Questionnaire"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DefinitionResourceType-list")
@XmlEnum
public enum DefinitionResourceTypeList {


    /**
     * ActivityDefinition
     * 
     */
    @XmlEnumValue("ActivityDefinition")
    ACTIVITY_DEFINITION("ActivityDefinition"),

    /**
     * EventDefinition
     * 
     */
    @XmlEnumValue("EventDefinition")
    EVENT_DEFINITION("EventDefinition"),

    /**
     * Measure
     * 
     */
    @XmlEnumValue("Measure")
    MEASURE("Measure"),

    /**
     * OperationDefinition
     * 
     */
    @XmlEnumValue("OperationDefinition")
    OPERATION_DEFINITION("OperationDefinition"),

    /**
     * PlanDefinition
     * 
     */
    @XmlEnumValue("PlanDefinition")
    PLAN_DEFINITION("PlanDefinition"),

    /**
     * Questionnaire
     * 
     */
    @XmlEnumValue("Questionnaire")
    QUESTIONNAIRE("Questionnaire");
    private final java.lang.String value;

    DefinitionResourceTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static DefinitionResourceTypeList fromValue(java.lang.String v) {
        for (DefinitionResourceTypeList c: DefinitionResourceTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
