//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an @id referenced from the Narrative, or extensions
 * 
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}Base">
 *       &lt;sequence>
 *         &lt;element name="extension" type="{http://hl7.org/fhir}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://hl7.org/fhir}string-primitive" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "extension"
})
@XmlSeeAlso({
    DiscriminatorType.class,
    AllergyIntoleranceType.class,
    CarePlanActivityStatus.class,
    LinkageType.class,
    ContractResourcePublicationStatusCodes.class,
    DeviceMetricCalibrationState.class,
    RequestPriority.class,
    OrientationType.class,
    CatalogEntryStatus.class,
    MedlineCitationOwner.class,
    StrandType.class,
    MedlineCitationStatus.class,
    RestfulCapabilityMode.class,
    ProvenanceEntityRole.class,
    TypeDerivationRule.class,
    SpecimenContainedPreference.class,
    DeviceMetricCategory.class,
    GraphCompartmentUse.class,
    Decimal.class,
    DocumentReferenceStatus.class,
    CapabilityStatementKind.class,
    TestReportParticipantType.class,
    CarePlanIntent.class,
    DetectedIssueSeverity.class,
    StructureMapInputMode.class,
    TestReportResult.class,
    ConsentDataMeaning.class,
    MedicationrequestStatus.class,
    AggregationMode.class,
    AppointmentStatus.class,
    QuestionnaireItemType.class,
    MedicationUsageStatusCodes.class,
    GroupMeasure.class,
    ImagingStudyStatus.class,
    RelatedArtifactType.class,
    MedicationRequestIntent.class,
    InventoryReportStatus.class,
    ConditionalReadStatus.class,
    ParticipationStatus.class,
    RequestResourceType.class,
    Instant.class,
    LocationMode.class,
    DocumentRelationshipType.class,
    ResourceVersionPolicy.class,
    AdministrativeGender.class,
    LinkType.class,
    EventTiming.class,
    ConceptMapGroupUnmappedMode.class,
    FamilyHistoryStatus.class,
    InventoryCountType.class,
    Base64Binary.class,
    SampledDataDataType.class,
    ActionRelationshipType.class,
    ObservationDataType.class,
    EpisodeOfCareStatus.class,
    AuditEventAgentNetworkType.class,
    ExampleScenarioActorType.class,
    CompositionAttestationMode.class,
    MeasureReportType.class,
    CodeSystemHierarchyMeaning.class,
    StructureMapTransform.class,
    ResearchSubjectStatus.class,
    ContributorType.class,
    RepositoryType.class,
    ConceptMapEquivalence.class,
    Markdown.class,
    IdentifierUse.class,
    StructureDefinitionKind.class,
    StructureMapTargetListMode.class,
    QualityType.class,
    SPDXLicense.class,
    MeasureReportStatus.class,
    MedicationStatusCodes.class,
    PublicationStatus.class,
    FHIRSubstanceStatus.class,
    ContactPointSystem.class,
    StructureMapModelMode.class,
    FHIRDeviceStatus.class,
    SequenceType.class,
    org.hl7.fhir.String.class,
    SpecimenStatus.class,
    EventStatus.class,
    SlicingRules.class,
    Time.class,
    ReferenceVersionRules.class,
    DocumentAttestationMode.class,
    HTTPVerb.class,
    NameUse.class,
    ConceptMapRelationship.class,
    MessageSignificanceCategory.class,
    GuidanceResponseStatus.class,
    SubscriptionPayloadContent.class,
    DaysOfWeek.class,
    ActionSelectionBehavior.class,
    EncounterStatus.class,
    TestReportStatus.class,
    AllergyIntoleranceCategory.class,
    EventCapabilityMode.class,
    AssertionDirectionType.class,
    MessageheaderResponseRequest.class,
    ObservationStatus.class,
    SubscriptionNotificationType.class,
    ActionParticipantType.class,
    QuestionnaireResponseStatus.class,
    CareTeamStatus.class,
    TestScriptRequestMethodCode.class,
    DeviceMetricOperationalStatus.class,
    Uuid.class,
    AccountStatus.class,
    TaskIntent.class,
    ExplanationOfBenefitStatus.class,
    EligibilityRequestPurpose.class,
    ImmunizationEvaluationStatusCodes.class,
    ActionConditionKind.class,
    ExtensionContextType.class,
    AgeUnits.class,
    PermissionStatus.class,
    ContactPointUse.class,
    InteractionTrigger.class,
    Confidentiality.class,
    QuestionnaireItemOperator.class,
    IdentityAssuranceLevel.class,
    ReportRelationshipType.class,
    ResearchStudyStatus.class,
    RequestIntent.class,
    ClaimProcessingCodes.class,
    BiologicallyDerivedProductStorageScale.class,
    LocationStatus.class,
    ConditionQuestionnairePurpose.class,
    NamingSystemIdentifierType.class,
    AdverseEventStatus.class,
    SlotStatus.class,
    VisionEyes.class,
    OperationKind.class,
    PubMedPubStatus.class,
    NoteType.class,
    AddressType.class,
    DefinitionResourceType.class,
    FinancialResourceStatusCodes.class,
    RequestStatus.class,
    FlagStatus.class,
    DocumentMode.class,
    EnableWhenBehavior.class,
    PropertyType.class,
    CharacteristicCombination.class,
    ResponseType.class,
    CompositionStatus.class,
    ChargeItemStatus.class,
    ContractResourceStatusCodes.class,
    RemittanceOutcome.class,
    SearchEntryMode.class,
    SubscriptionUrlLocation.class,
    EvidenceVariableHandling.class,
    MedicationDispenseStatusCodes.class,
    NarrativeStatus.class,
    SortDirection.class,
    GuidePageGeneration.class,
    UnitsOfTime.class,
    SearchComparator.class,
    UnsignedInt.class,
    Id.class,
    Integer64 .class,
    CatalogEntryType.class,
    GroupType.class,
    GoalLifecycleStatus.class,
    Status.class,
    DateTime.class,
    CarePlanActivityKind.class,
    Use.class,
    GraphCompartmentRule.class,
    ImmunizationStatusCodes.class,
    TaskStatus.class,
    Uri.class,
    Url.class,
    DeviceMetricCalibrationType.class,
    TestReportActionResult.class,
    ClinicalUseIssueType.class,
    Integer.class,
    NutritionProductStatus.class,
    MedicationAdministrationStatusCodes.class,
    CatalogEntryRelationType.class,
    Canonical.class,
    IssueSeverity.class,
    Code.class,
    PropertyRepresentation.class,
    Oid.class,
    SupplyDeliveryStatus.class,
    IssueType.class,
    ConditionPreconditionType.class,
    DeviceMetricColor.class,
    SearchParamType.class,
    NamingSystemType.class,
    FHIRVersion.class,
    ActionCardinalityBehavior.class,
    VisionBase.class,
    BundleType.class,
    AllergyIntoleranceSeverity.class,
    KnowledgeResourceType.class,
    TriggerType.class,
    EventResourceType.class,
    SystemRestfulInteraction.class,
    PublicationStatusTkalatz.class,
    ConsentProvisionType.class,
    FilterOperator.class,
    SupplyRequestStatus.class,
    QuantityComparator.class,
    ReferenceHandlingPolicy.class,
    OperationParameterUse.class,
    ObservationRangeCategory.class,
    ResourceType.class,
    ActionRequiredBehavior.class,
    BindingStrength.class,
    ActionGroupingBehavior.class,
    AuditEventSeverity.class,
    StructureMapSourceListMode.class,
    EligibilityResponsePurpose.class,
    ConsentState.class,
    SearchModifierCode.class,
    AllergyIntoleranceCriticality.class,
    XPathUsageType.class,
    DeviceUseStatementStatus.class,
    ListStatus.class,
    ConditionalDeleteStatus.class,
    UDIEntryType.class,
    AuditEventAction.class,
    AdverseEventActuality.class,
    ParticipantRequired.class,
    Event_0020Or_0020Request_0020Resource_0020Types.class,
    PositiveInt.class,
    BiologicallyDerivedProductCategory.class,
    AssertionResponseTypes.class,
    TypeRestfulInteraction.class,
    DiagnosticReportStatus.class,
    InvoicePriceComponentType.class,
    CodeSystemContentMode.class,
    ActionPrecheckBehavior.class,
    InvoiceStatus.class,
    Date.class,
    StructureMapGroupTypeMode.class,
    ConstraintSeverity.class,
    ListMode.class,
    CodeSearchSupport.class,
    AssertionOperatorType.class,
    EndpointStatus.class,
    DeviceNameType.class,
    CriteriaNotExistsBehavior.class,
    AddressUse.class,
    CompartmentType.class,
    BiologicallyDerivedProductStatus.class,
    Boolean.class,
    BackboneElement.class,
    EncounterLocationStatus.class,
    DataType.class
})
public class Element
    extends Base
{

    protected List<Extension> extension;
    @XmlAttribute(name = "id")
    protected java.lang.String id;

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
