//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about a medication that is used to support knowledge.
 * 
 * <p>Java class for MedicationKnowledge.Cost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicationKnowledge.Cost">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="effectiveDate" type="{http://hl7.org/fhir}Period" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type" type="{http://hl7.org/fhir}CodeableConcept"/>
 *         &lt;element name="source" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="costMoney" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="costCodeableConcept" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicationKnowledge.Cost", propOrder = {
    "effectiveDate",
    "type",
    "source",
    "costMoney",
    "costCodeableConcept"
})
public class MedicationKnowledgeCost
    extends BackboneElement
{

    protected List<Period> effectiveDate;
    @XmlElement(required = true)
    protected CodeableConcept type;
    protected String source;
    protected Money costMoney;
    protected CodeableConcept costCodeableConcept;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectiveDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectiveDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Period }
     * 
     * 
     */
    public List<Period> getEffectiveDate() {
        if (effectiveDate == null) {
            effectiveDate = new ArrayList<Period>();
        }
        return this.effectiveDate;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setType(CodeableConcept value) {
        this.type = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the costMoney property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getCostMoney() {
        return costMoney;
    }

    /**
     * Sets the value of the costMoney property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setCostMoney(Money value) {
        this.costMoney = value;
    }

    /**
     * Gets the value of the costCodeableConcept property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getCostCodeableConcept() {
        return costCodeableConcept;
    }

    /**
     * Sets the value of the costCodeableConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setCostCodeableConcept(CodeableConcept value) {
        this.costCodeableConcept = value;
    }

}
