//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceVersionRules-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferenceVersionRules-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="either"/>
 *     &lt;enumeration value="independent"/>
 *     &lt;enumeration value="specific"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReferenceVersionRules-list")
@XmlEnum
public enum ReferenceVersionRulesList {


    /**
     * Either Specific or independent
     * 
     */
    @XmlEnumValue("either")
    EITHER("either"),

    /**
     * Version independent
     * 
     */
    @XmlEnumValue("independent")
    INDEPENDENT("independent"),

    /**
     * Version Specific
     * 
     */
    @XmlEnumValue("specific")
    SPECIFIC("specific");
    private final java.lang.String value;

    ReferenceVersionRulesList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ReferenceVersionRulesList fromValue(java.lang.String v) {
        for (ReferenceVersionRulesList c: ReferenceVersionRulesList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
