//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructureMapTargetListMode-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StructureMapTargetListMode-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="first"/>
 *     &lt;enumeration value="share"/>
 *     &lt;enumeration value="last"/>
 *     &lt;enumeration value="collate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StructureMapTargetListMode-list")
@XmlEnum
public enum StructureMapTargetListModeList {


    /**
     * First
     * 
     */
    @XmlEnumValue("first")
    FIRST("first"),

    /**
     * Share
     * 
     */
    @XmlEnumValue("share")
    SHARE("share"),

    /**
     * Last
     * 
     */
    @XmlEnumValue("last")
    LAST("last"),

    /**
     * Collate
     * 
     */
    @XmlEnumValue("collate")
    COLLATE("collate");
    private final java.lang.String value;

    StructureMapTargetListModeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static StructureMapTargetListModeList fromValue(java.lang.String v) {
        for (StructureMapTargetListModeList c: StructureMapTargetListModeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
