//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.11 at 03:47:56 PM EET 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The detailed description of a substance, typically at a level beyond what is used for prescribing.
 * 
 * <p>Java class for SubstanceDefinition.Structure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstanceDefinition.Structure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="stereochemistry" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="opticalActivity" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="molecularFormula" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="molecularFormulaByMoiety" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="isotope" type="{http://hl7.org/fhir}SubstanceDefinition.Isotope" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="molecularWeight" type="{http://hl7.org/fhir}SubstanceDefinition.MolecularWeight" minOccurs="0"/>
 *         &lt;element name="technique" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sourceDocument" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="representation" type="{http://hl7.org/fhir}SubstanceDefinition.Representation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstanceDefinition.Structure", propOrder = {
    "stereochemistry",
    "opticalActivity",
    "molecularFormula",
    "molecularFormulaByMoiety",
    "isotope",
    "molecularWeight",
    "technique",
    "sourceDocument",
    "representation"
})
public class SubstanceDefinitionStructure
    extends BackboneElement
{

    protected CodeableConcept stereochemistry;
    protected CodeableConcept opticalActivity;
    protected String molecularFormula;
    protected String molecularFormulaByMoiety;
    protected List<SubstanceDefinitionIsotope> isotope;
    protected SubstanceDefinitionMolecularWeight molecularWeight;
    protected List<CodeableConcept> technique;
    protected List<Reference> sourceDocument;
    protected List<SubstanceDefinitionRepresentation> representation;

    /**
     * Gets the value of the stereochemistry property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getStereochemistry() {
        return stereochemistry;
    }

    /**
     * Sets the value of the stereochemistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setStereochemistry(CodeableConcept value) {
        this.stereochemistry = value;
    }

    /**
     * Gets the value of the opticalActivity property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getOpticalActivity() {
        return opticalActivity;
    }

    /**
     * Sets the value of the opticalActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setOpticalActivity(CodeableConcept value) {
        this.opticalActivity = value;
    }

    /**
     * Gets the value of the molecularFormula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMolecularFormula() {
        return molecularFormula;
    }

    /**
     * Sets the value of the molecularFormula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMolecularFormula(String value) {
        this.molecularFormula = value;
    }

    /**
     * Gets the value of the molecularFormulaByMoiety property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMolecularFormulaByMoiety() {
        return molecularFormulaByMoiety;
    }

    /**
     * Sets the value of the molecularFormulaByMoiety property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMolecularFormulaByMoiety(String value) {
        this.molecularFormulaByMoiety = value;
    }

    /**
     * Gets the value of the isotope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isotope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsotope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceDefinitionIsotope }
     * 
     * 
     */
    public List<SubstanceDefinitionIsotope> getIsotope() {
        if (isotope == null) {
            isotope = new ArrayList<SubstanceDefinitionIsotope>();
        }
        return this.isotope;
    }

    /**
     * Gets the value of the molecularWeight property.
     * 
     * @return
     *     possible object is
     *     {@link SubstanceDefinitionMolecularWeight }
     *     
     */
    public SubstanceDefinitionMolecularWeight getMolecularWeight() {
        return molecularWeight;
    }

    /**
     * Sets the value of the molecularWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstanceDefinitionMolecularWeight }
     *     
     */
    public void setMolecularWeight(SubstanceDefinitionMolecularWeight value) {
        this.molecularWeight = value;
    }

    /**
     * Gets the value of the technique property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technique property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnique().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getTechnique() {
        if (technique == null) {
            technique = new ArrayList<CodeableConcept>();
        }
        return this.technique;
    }

    /**
     * Gets the value of the sourceDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getSourceDocument() {
        if (sourceDocument == null) {
            sourceDocument = new ArrayList<Reference>();
        }
        return this.sourceDocument;
    }

    /**
     * Gets the value of the representation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepresentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceDefinitionRepresentation }
     * 
     * 
     */
    public List<SubstanceDefinitionRepresentation> getRepresentation() {
        if (representation == null) {
            representation = new ArrayList<SubstanceDefinitionRepresentation>();
        }
        return this.representation;
    }

}
